---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: images
  type: image_gallery
  config: {}
  label: images
- name: color
  type: color
  config:
    required: false
    color_format: Hex
  label: color
pages:
- content/projects/softsurplus.md
