---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: images
  type: image_gallery
  config: {}
  label: images
- name: color
  type: color
  config:
    required: false
    color_format: Hex
  label: color
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: publish
  type: boolean
  label: Publish
- name: date
  type: text
  config:
    required: false
  label: Date
pages:
- content/projects/cybernetics-library.md
- content/projects/cybernetics-library.md
- content/projects/primeproduce.md
- content/projects/primeproduce.md
- content/projects/softsurplus.md
- content/projects/softsurplus.md
